using System;



namespace Nikki.Utils.DDS
{
	internal enum DDS_VOLUME : uint
	{
        CUBEMAP = 0x00000200, // DDSCAPS2_CUBEMAP
        FLAGS_VOLUME = 0x00200000, // DDSCAPS2_VOLUME
        CUBEMAP_POSITIVEX = 0x00000600, // DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_POSITIVEX
        CUBEMAP_NEGATIVEX = 0x00000A00, // DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_NEGATIVEX
        CUBEMAP_POSITIVEY = 0x00001200, // DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_POSITIVEY
        CUBEMAP_NEGATIVEY = 0x00002200, // DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_NEGATIVEY
        CUBEMAP_POSITIVEZ = 0x00004200, // DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_POSITIVEZ
        CUBEMAP_NEGATIVEZ = 0x00008200, // DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_NEGATIVEZ
        CUBEMAP_ALLFACES = CUBEMAP_POSITIVEX | CUBEMAP_POSITIVEY | CUBEMAP_POSITIVEZ |
                                                CUBEMAP_NEGATIVEX | CUBEMAP_NEGATIVEY | CUBEMAP_NEGATIVEZ,
    }
}
